name: Go

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']

permissions:
  contents: read

jobs:

  build:
    runs-on: ${{ matrix.os }}
    name: Test (Go ${{ matrix.go }} / ${{ matrix.os }})
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        go: ["1.21.x", "1.22.x"]

    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Dependencies
      run: go mod download

    - name: Test
      run: make cover

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.x
        cache: false  # managed by golangci-lint

    - uses: golangci/golangci-lint-action@v3
      name: Install golangci-lint
      with:
        version: latest
        args: --help  # make lint will run the linter

    - run: make lint
      name: Lint
